---
title: "CodeBook for Getting and Cleaning Assignment"
author: "Koustubh Kelapure"
date: "June 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The cleaned version of data is present in two versions:
1. Text format - tidy.txt
2. CSV format - tidy.csv

Look at the readme file to gain a rough context about how the dataset is cleaned.
There are 3 sections in the document:
1. Data - Describes the structure of the data 
2. Variables - Brief descriptions of the variables in the dataset 
3. Transformations - Explains the transformations carried out on the data to get it in a clean and tidy format

### Data 
The tidy.txt data file is a text file, containing space-separated values.
The first row contains the names of the variables and the following rows contain the values of these variables.

### Variables

#### Identifiers
  * subject - Subject identifier, which is an integer ranging from 1 to 30
  * activity - String with 6 possible values, describes what activity the subject was performing 
    + WALKING 
    + WALKING_UPSTAIRS
    + WALKING_DOWNSTAIRS
    + SITTING
    + STANDING 
    + LAYING

#### Average of measurement 
All measurements are floating-point values, normalised and bounded within [-1,1]. The measurements are classified in two domains:
  * Time Domain(Prefix - timedomain) - resulting from the capture of accelerometer and gyroscope raw signals.
  * Frequency Domain(Prefix - frequencydomain) - resulting from the application of a Fast Fourier Transform (FFT) to some of the time-domain signals.

##### Time Domain Variables 

  * timeDomainBodyAccelerometerMeanX
  * timeDomainBodyAccelerometerMeanY
  * timeDomainBodyAccelerometerMeanZ
  
  * timeDomainBodyAccelerometerStandardDeviationX
  * timeDomainBodyAccelerometerStandardDeviationY
  * timeDomainBodyAccelerometerStandardDeviationZ
  
  * timeDomainGravityAccelerometerMeanX
  * timeDomainGravityAccelerometerMeanY
  * timeDomainGravityAccelerometerMeanZ
  
  * timeDomainGravityAccelerometerStandardDeviationX
  * timeDomainGravityAccelerometerStandardDeviationY
  * timeDomainGravityAccelerometerStandardDeviationZ
  
  * timeDomainBodyAccelerometerJerkMeanX
  * timeDomainBodyAccelerometerJerkMeanY
  * timeDomainBodyAccelerometerJerkMeanZ
  
  * timeDomainBodyAccelerometerJerkStandardDeviationX
  * timeDomainBodyAccelerometerJerkStandardDeviationY
  * timeDomainBodyAccelerometerJerkStandardDeviationZ
  
  * timeDomainBodyGyroscopeMeanX
  * timeDomainBodyGyroscopeMeanY
  * timeDomainBodyGyroscopeMeanZ
  
  * timeDomainBodyGyroscopeStandardDeviationX
  * timeDomainBodyGyroscopeStandardDeviationY
  * timeDomainBodyGyroscopeStandardDeviationZ
  
  * timeDomainBodyGyroscopeJerkMeanX
  * timeDomainBodyGyroscopeJerkMeanY
  * timeDomainBodyGyroscopeJerkMeanZ
  
  * timeDomainBodyGyroscopeJerkStandardDeviationX
  * timeDomainBodyGyroscopeJerkStandardDeviationY
  * timeDomainBodyGyroscopeJerkStandardDeviationZ
  
  * timeDomainBodyAccelerometerMagnitudeMean
  * timeDomainBodyAccelerometerMagnitudeStandardDeviation
  
  * timeDomainGravityAccelerometerMagnitudeMean
  * timeDomainGravityAccelerometerMagnitudeStandardDeviation
  
  * timeDomainBodyAccelerometerJerkMagnitudeMean
  * timeDomainBodyAccelerometerJerkMagnitudeStandardDeviation
  
  * timeDomainBodyGyroscopeMagnitudeMean
  * timeDomainBodyGyroscopeMagnitudeStandardDeviation
  
  * timeDomainBodyGyroscopeJerkMagnitudeMean
  * timeDomainBodyGyroscopeJerkMagnitudeStandardDeviation
  
##### Frequency Domain Variables 

  * frequencyDomainBodyAccelerometerMeanX
  * frequencyDomainBodyAccelerometerMeanY 
  * frequencyDomainBodyAccelerometerMeanZ
  
  * frequencyDomainBodyAccelerometerStandardDeviationX
  * frequencyDomainBodyAccelerometerStandardDeviationY
  * frequencyDomainBodyAccelerometerStandardDeviationZ
  
  * frequencyDomainBodyAccelerometerMeanFrequencyX
  * frequencyDomainBodyAccelerometerMeanFrequencyY
  * frequencyDomainBodyAccelerometerMeanFrequencyZ
  
  * frequencyDomainBodyAccelerometerJerkMeanX
  * frequencyDomainBodyAccelerometerJerkMeanY
  * frequencyDomainBodyAccelerometerJerkMeanZ
  
  * frequencyDomainBodyAccelerometerJerkStandardDeviationX
  * frequencyDomainBodyAccelerometerJerkStandardDeviationY
  * frequencyDomainBodyAccelerometerJerkStandardDeviationZ
  
  * frequencyDomainBodyAccelerometerJerkMeanFrequencyX
  * frequencyDomainBodyAccelerometerJerkMeanFrequencyY 
  * frequencyDomainBodyAccelerometerJerkMeanFrequencyZ
  
  * frequencyDomainBodyGyroscopeMeanX
  * frequencyDomainBodyGyroscopeMeanY
  * frequencyDomainBodyGyroscopeMeanZ
  
  * frequencyDomainBodyGyroscopeStandardDeviationX
  * frequencyDomainBodyGyroscopeStandardDeviationY
  * frequencyDomainBodyGyroscopeStandardDeviationZ
  
  * frequencyDomainBodyGyroscopeMeanFrequencyX
  * frequencyDomainBodyGyroscopeMeanFrequencyY
  * frequencyDomainBodyGyroscopeMeanFrequencyZ
  
  * frequencyDomainBodyAccelerometerMagnitudeMean
  * frequencyDomainBodyAccelerometerMagnitudeStandardDeviation
  * frequencyDomainBodyAccelerometerMagnitudeMeanFrequency
  
  * frequencyDomainBodyAccelerometerJerkMagnitudeMean
  * frequencyDomainBodyAccelerometerJerkMagnitudeStandardDeviation
  * frequencyDomainBodyAccelerometerJerkMagnitudeMeanFrequency
  
  * frequencyDomainBodyGyroscopeMagnitudeMean
  * frequencyDomainBodyGyroscopeMagnitudeStandardDeviation
  * frequencyDomainBodyGyroscopeMagnitudeMeanFrequency
  
  * frequencyDomainBodyGyroscopeJerkMagnitudeMean
  * frequencyDomainBodyGyroscopeJerkMagnitudeStandardDeviation
  * frequencyDomainBodyGyroscopeJerkMagnitudeMeanFrequency

### Transformations

  * The following transformations were applied to the data o make it clean and usable for further use 
    + The training and test sets were merged to create one data set.
    + he measurements on the mean and standard deviation (i.e. signals containing the strings mean and std) were extracted for each measurement, and the others were discarded.
    + The activity identifiers (originally coded as integers between 1 and 6) were replaced with descriptive activity names (see Identifiers section).
    + The variable names were replaced with descriptive variable names (e.g. tBodyAcc-mean()-X was expanded to timeDomainBodyAccelerometerMeanX), using the following set of rules:
        - Special characters (i.e. (, ), and -) were removed
        - The initial f and t were expanded to frequencyDomain and timeDomain respectively.
        - Acc, Gyro, Mag, Freq, mean, and std were replaced with Accelerometer, Gyroscope, Magnitude, Frequency, Mean, and StandardDeviation respectively.
        - Replaced (supposedly incorrect as per source's features_info.txt file) BodyBody with Body.
    + From the data set in step 4, the final data set was created with the average of each variable for each activity and each subject.


  